apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: chart2
spec:
  replicas: 5
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate01
        args:
        - name: service-name
          value: chart2
      canaryService: chart2-canary
      stableService: chart2
      trafficRouting:
        nginx:
          stableIngress: chart2
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: chart2
  template:
    metadata:
      labels:
        app: chart2
    spec:
      containers:
      - name: chart2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
